/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RaffleStatus = IDL.Variant({
  'closed' : IDL.Null,
  'upcoming' : IDL.Null,
  'open' : IDL.Null,
  'drawn' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Time = IDL.Int;
export const RaffleAdminConfig = IDL.Record({
  'drawTimestamp' : Time,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'totalSpots' : IDL.Nat,
  'spotPriceCents' : IDL.Nat,
  'prizeAmountCents' : IDL.Nat,
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const Raffle = IDL.Record({
  'id' : IDL.Nat,
  'drawTimestamp' : Time,
  'status' : RaffleStatus,
  'title' : IDL.Text,
  'lastUpdated' : Time,
  'winner' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'createdTime' : Time,
  'drawRecordId' : IDL.Opt(IDL.Text),
  'totalSpots' : IDL.Nat,
  'spotPriceCents' : IDL.Nat,
  'prizeAmountCents' : IDL.Nat,
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Entry = IDL.Record({
  'id' : IDL.Nat,
  'raffleId' : IDL.Nat,
  'purchaseTime' : Time,
  'isPaid' : IDL.Bool,
  'quantity' : IDL.Nat,
  'buyer' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeStatus' : IDL.Func([IDL.Nat, RaffleStatus], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createRaffle' : IDL.Func([RaffleAdminConfig], [IDL.Nat], []),
  'getActiveRaffles' : IDL.Func([], [IDL.Vec(Raffle)], ['query']),
  'getAllRaffles' : IDL.Func([], [IDL.Vec(Raffle)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletedRaffles' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'id' : IDL.Nat,
            'drawTimestamp' : Time,
            'title' : IDL.Text,
            'participants' : IDL.Nat,
            'winner' : IDL.Opt(IDL.Text),
            'spotsSold' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getEntries' : IDL.Func([IDL.Nat], [IDL.Vec(Entry)], ['query']),
  'getLiveRaffle' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'timeToDraw' : IDL.Int,
          'entries' : IDL.Vec(Entry),
          'raffle' : Raffle,
        }),
      ],
      ['query'],
    ),
  'getRemainingSpots' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'purchaseEntries' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'triggerDraw' : IDL.Func([IDL.Nat], [], []),
  'updateRaffle' : IDL.Func([IDL.Nat, RaffleAdminConfig], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RaffleStatus = IDL.Variant({
    'closed' : IDL.Null,
    'upcoming' : IDL.Null,
    'open' : IDL.Null,
    'drawn' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Time = IDL.Int;
  const RaffleAdminConfig = IDL.Record({
    'drawTimestamp' : Time,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'totalSpots' : IDL.Nat,
    'spotPriceCents' : IDL.Nat,
    'prizeAmountCents' : IDL.Nat,
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const Raffle = IDL.Record({
    'id' : IDL.Nat,
    'drawTimestamp' : Time,
    'status' : RaffleStatus,
    'title' : IDL.Text,
    'lastUpdated' : Time,
    'winner' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'createdTime' : Time,
    'drawRecordId' : IDL.Opt(IDL.Text),
    'totalSpots' : IDL.Nat,
    'spotPriceCents' : IDL.Nat,
    'prizeAmountCents' : IDL.Nat,
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Entry = IDL.Record({
    'id' : IDL.Nat,
    'raffleId' : IDL.Nat,
    'purchaseTime' : Time,
    'isPaid' : IDL.Bool,
    'quantity' : IDL.Nat,
    'buyer' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeStatus' : IDL.Func([IDL.Nat, RaffleStatus], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createRaffle' : IDL.Func([RaffleAdminConfig], [IDL.Nat], []),
    'getActiveRaffles' : IDL.Func([], [IDL.Vec(Raffle)], ['query']),
    'getAllRaffles' : IDL.Func([], [IDL.Vec(Raffle)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletedRaffles' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'id' : IDL.Nat,
              'drawTimestamp' : Time,
              'title' : IDL.Text,
              'participants' : IDL.Nat,
              'winner' : IDL.Opt(IDL.Text),
              'spotsSold' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getEntries' : IDL.Func([IDL.Nat], [IDL.Vec(Entry)], ['query']),
    'getLiveRaffle' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'timeToDraw' : IDL.Int,
            'entries' : IDL.Vec(Entry),
            'raffle' : Raffle,
          }),
        ],
        ['query'],
      ),
    'getRemainingSpots' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'purchaseEntries' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'triggerDraw' : IDL.Func([IDL.Nat], [], []),
    'updateRaffle' : IDL.Func([IDL.Nat, RaffleAdminConfig], [], []),
  });
};

export const init = ({ IDL }) => { return []; };