/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Entry {
  'id' : bigint,
  'raffleId' : bigint,
  'purchaseTime' : Time,
  'isPaid' : boolean,
  'quantity' : bigint,
  'buyer' : string,
}
export interface Raffle {
  'id' : bigint,
  'drawTimestamp' : Time,
  'status' : RaffleStatus,
  'title' : string,
  'lastUpdated' : Time,
  'winner' : [] | [string],
  'description' : string,
  'createdTime' : Time,
  'drawRecordId' : [] | [string],
  'totalSpots' : bigint,
  'spotPriceCents' : bigint,
  'prizeAmountCents' : bigint,
  'videoUrl' : [] | [string],
}
export interface RaffleAdminConfig {
  'drawTimestamp' : Time,
  'title' : string,
  'description' : string,
  'totalSpots' : bigint,
  'spotPriceCents' : bigint,
  'prizeAmountCents' : bigint,
  'videoUrl' : [] | [string],
}
export type RaffleStatus = { 'closed' : null } |
  { 'upcoming' : null } |
  { 'open' : null } |
  { 'drawn' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeStatus' : ActorMethod<[bigint, RaffleStatus], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createRaffle' : ActorMethod<[RaffleAdminConfig], bigint>,
  'getActiveRaffles' : ActorMethod<[], Array<Raffle>>,
  'getAllRaffles' : ActorMethod<[], Array<Raffle>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletedRaffles' : ActorMethod<
    [],
    Array<
      {
        'id' : bigint,
        'drawTimestamp' : Time,
        'title' : string,
        'participants' : bigint,
        'winner' : [] | [string],
        'spotsSold' : bigint,
      }
    >
  >,
  'getEntries' : ActorMethod<[bigint], Array<Entry>>,
  'getLiveRaffle' : ActorMethod<
    [bigint],
    { 'timeToDraw' : bigint, 'entries' : Array<Entry>, 'raffle' : Raffle }
  >,
  'getRemainingSpots' : ActorMethod<[bigint], bigint>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'purchaseEntries' : ActorMethod<[string, bigint, bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'triggerDraw' : ActorMethod<[bigint], undefined>,
  'updateRaffle' : ActorMethod<[bigint, RaffleAdminConfig], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];