/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface Raffle {
    id: bigint;
    drawTimestamp: Time;
    status: RaffleStatus;
    title: string;
    lastUpdated: Time;
    winner?: string;
    description: string;
    createdTime: Time;
    drawRecordId?: string;
    totalSpots: bigint;
    spotPriceCents: bigint;
    prizeAmountCents: bigint;
    videoUrl?: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Entry {
    id: bigint;
    raffleId: bigint;
    purchaseTime: Time;
    isPaid: boolean;
    quantity: bigint;
    buyer: string;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface RaffleAdminConfig {
    drawTimestamp: Time;
    title: string;
    description: string;
    totalSpots: bigint;
    spotPriceCents: bigint;
    prizeAmountCents: bigint;
    videoUrl?: string;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface UserProfile {
    name: string;
}
export enum RaffleStatus {
    closed = "closed",
    upcoming = "upcoming",
    open = "open",
    drawn = "drawn"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    changeStatus(id: bigint, newStatus: RaffleStatus): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createRaffle(config: RaffleAdminConfig): Promise<bigint>;
    getActiveRaffles(): Promise<Array<Raffle>>;
    getAllRaffles(): Promise<Array<Raffle>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompletedRaffles(): Promise<Array<{
        id: bigint;
        drawTimestamp: Time;
        title: string;
        participants: bigint;
        winner?: string;
        spotsSold: bigint;
    }>>;
    getEntries(raffleId: bigint): Promise<Array<Entry>>;
    getLiveRaffle(id: bigint): Promise<{
        timeToDraw: bigint;
        entries: Array<Entry>;
        raffle: Raffle;
    }>;
    getRemainingSpots(raffleId: bigint): Promise<bigint>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    purchaseEntries(buyerPid: string, raffleId: bigint, quantity: bigint, _quantityConfirmed: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    triggerDraw(id: bigint): Promise<void>;
    updateRaffle(id: bigint, config: RaffleAdminConfig): Promise<void>;
}
import type { Entry as _Entry, Raffle as _Raffle, RaffleAdminConfig as _RaffleAdminConfig, RaffleStatus as _RaffleStatus, StripeSessionStatus as _StripeSessionStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async changeStatus(arg0: bigint, arg1: RaffleStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.changeStatus(arg0, to_candid_RaffleStatus_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeStatus(arg0, to_candid_RaffleStatus_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createRaffle(arg0: RaffleAdminConfig): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createRaffle(to_candid_RaffleAdminConfig_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRaffle(to_candid_RaffleAdminConfig_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getActiveRaffles(): Promise<Array<Raffle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveRaffles();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveRaffles();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRaffles(): Promise<Array<Raffle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRaffles();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRaffles();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompletedRaffles(): Promise<Array<{
        id: bigint;
        drawTimestamp: Time;
        title: string;
        participants: bigint;
        winner?: string;
        spotsSold: bigint;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompletedRaffles();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompletedRaffles();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEntries(arg0: bigint): Promise<Array<Entry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntries(arg0);
            return result;
        }
    }
    async getLiveRaffle(arg0: bigint): Promise<{
        timeToDraw: bigint;
        entries: Array<Entry>;
        raffle: Raffle;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getLiveRaffle(arg0);
                return from_candid_record_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLiveRaffle(arg0);
            return from_candid_record_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRemainingSpots(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getRemainingSpots(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRemainingSpots(arg0);
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async purchaseEntries(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.purchaseEntries(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchaseEntries(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async triggerDraw(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.triggerDraw(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.triggerDraw(arg0);
            return result;
        }
    }
    async updateRaffle(arg0: bigint, arg1: RaffleAdminConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRaffle(arg0, to_candid_RaffleAdminConfig_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRaffle(arg0, to_candid_RaffleAdminConfig_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_RaffleStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RaffleStatus): RaffleStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Raffle_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Raffle): Raffle {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    drawTimestamp: _Time;
    title: string;
    participants: bigint;
    winner: [] | [string];
    spotsSold: bigint;
}): {
    id: bigint;
    drawTimestamp: Time;
    title: string;
    participants: bigint;
    winner?: string;
    spotsSold: bigint;
} {
    return {
        id: value.id,
        drawTimestamp: value.drawTimestamp,
        title: value.title,
        participants: value.participants,
        winner: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.winner)),
        spotsSold: value.spotsSold
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timeToDraw: bigint;
    entries: Array<_Entry>;
    raffle: _Raffle;
}): {
    timeToDraw: bigint;
    entries: Array<Entry>;
    raffle: Raffle;
} {
    return {
        timeToDraw: value.timeToDraw,
        entries: value.entries,
        raffle: from_candid_Raffle_n8(_uploadFile, _downloadFile, value.raffle)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    drawTimestamp: _Time;
    status: _RaffleStatus;
    title: string;
    lastUpdated: _Time;
    winner: [] | [string];
    description: string;
    createdTime: _Time;
    drawRecordId: [] | [string];
    totalSpots: bigint;
    spotPriceCents: bigint;
    prizeAmountCents: bigint;
    videoUrl: [] | [string];
}): {
    id: bigint;
    drawTimestamp: Time;
    status: RaffleStatus;
    title: string;
    lastUpdated: Time;
    winner?: string;
    description: string;
    createdTime: Time;
    drawRecordId?: string;
    totalSpots: bigint;
    spotPriceCents: bigint;
    prizeAmountCents: bigint;
    videoUrl?: string;
} {
    return {
        id: value.id,
        drawTimestamp: value.drawTimestamp,
        status: from_candid_RaffleStatus_n10(_uploadFile, _downloadFile, value.status),
        title: value.title,
        lastUpdated: value.lastUpdated,
        winner: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.winner)),
        description: value.description,
        createdTime: value.createdTime,
        drawRecordId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.drawRecordId)),
        totalSpots: value.totalSpots,
        spotPriceCents: value.spotPriceCents,
        prizeAmountCents: value.prizeAmountCents,
        videoUrl: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.videoUrl))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    upcoming: null;
} | {
    open: null;
} | {
    drawn: null;
}): RaffleStatus {
    return "closed" in value ? RaffleStatus.closed : "upcoming" in value ? RaffleStatus.upcoming : "open" in value ? RaffleStatus.open : "drawn" in value ? RaffleStatus.drawn : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n21(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    id: bigint;
    drawTimestamp: _Time;
    title: string;
    participants: bigint;
    winner: [] | [string];
    spotsSold: bigint;
}>): Array<{
    id: bigint;
    drawTimestamp: Time;
    title: string;
    participants: bigint;
    winner?: string;
    spotsSold: bigint;
}> {
    return value.map((x)=>from_candid_record_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Raffle>): Array<Raffle> {
    return value.map((x)=>from_candid_Raffle_n8(_uploadFile, _downloadFile, x));
}
function to_candid_RaffleAdminConfig_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RaffleAdminConfig): _RaffleAdminConfig {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_RaffleStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RaffleStatus): _RaffleStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    drawTimestamp: Time;
    title: string;
    description: string;
    totalSpots: bigint;
    spotPriceCents: bigint;
    prizeAmountCents: bigint;
    videoUrl?: string;
}): {
    drawTimestamp: _Time;
    title: string;
    description: string;
    totalSpots: bigint;
    spotPriceCents: bigint;
    prizeAmountCents: bigint;
    videoUrl: [] | [string];
} {
    return {
        drawTimestamp: value.drawTimestamp,
        title: value.title,
        description: value.description,
        totalSpots: value.totalSpots,
        spotPriceCents: value.spotPriceCents,
        prizeAmountCents: value.prizeAmountCents,
        videoUrl: value.videoUrl ? candid_some(value.videoUrl) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RaffleStatus): {
    closed: null;
} | {
    upcoming: null;
} | {
    open: null;
} | {
    drawn: null;
} {
    return value == RaffleStatus.closed ? {
        closed: null
    } : value == RaffleStatus.upcoming ? {
        upcoming: null
    } : value == RaffleStatus.open ? {
        open: null
    } : value == RaffleStatus.drawn ? {
        drawn: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
